### ISSUE TITLE
Question about changing an existing ad

### ISSUE THREAD

**Issue by 2food** [navikt/pam-import-api#24]
As far as I can see in the API docs, there's no way to change an ad once it's published.
You could deactivate it and re-publish it, but given that you have a manual approval process I assume that you don't want us to do this, unless absolutely necessary.  

Is there any recommended way to do this?

**Comment by tuantrannav** [comment]
Hi!

It is possible to change an ad once its published (approved), As soon as the ad has been approved once, it will get automatically approved on next update. 


> As far as I can see in the API docs, there's no way to change an ad once it's published.
> You could deactivate it and re-publish it, but given that you have a manual approval process I assume that you don't want us to do this, unless absolutely necessary.
> 
> Is there any recommended way to do this?

**Comment by 2food** [comment]
@tuantrannav Ah, okay. Thanks for the help!
