### ISSUE TITLE
Deactivate ad on test env

### ISSUE THREAD

**Issue by AlexSt2501** [navikt/pam-import-api#30]
Deactivate method works incorrect.
I got **RECEIVED** status in a response. When I check status I again got **DONE** status and ad still visible.
How I can reach **DELETED** status?

**Comment by tuantrannav** [comment]
Could you give me the url for preview the ad? or the uuid or reference?

**Comment by AlexSt2501** [comment]
6ff96097-de81-4430-a648-3edc12e073e0

**Comment by tuantrannav** [comment]
This Ad has correct status, expiration date is set to "expires" : "2020-11-17T14:20:43.751165".  We dont have "DELETED" as status 

enum class Status {
    RECEIVED, PENDING, DONE, UNKNOWN
}

However there is bug in the frontend though, it should show "inaktiv". This will be fixed soon.

**Comment by AlexSt2501** [comment]
@tuantrannav Thanks!
Is it possible to add a new parameter (adminstatus method) to the response, like **isActive: bool**? Because now it is really impossible to know the current state of ad(the same status **DONE** after creation and delete)

**Comment by tuantrannav** [comment]
Can you create another issue, we will see if we can implement it someway.
