### ISSUE TITLE
Question about approve ad in production

### ISSUE THREAD

**Issue by AlexSt2501** [navikt/pam-import-api#31]
Why I always get 404 for 'adminstatus' method?

https://arbeidsplassen-api.nav.no/stillingsimport/api/v1/adminstatus/10041/174528

{
    "message": "AdAdminStatus for 10041, 174528 not found",
    "errorType": "NOT_FOUND",
    "errorRef": "1cbb5551-23d6-4b60-81bc-603e71d8be47"
}

References for example: 174451, 174342, 174528, 174529

Is it ok until ad will be approved?

**Comment by tuantrannav** [comment]
Hi,
There was abit of delay because of an error in the system. It is now fixed.
Usually if the ad contains prefilled category and employer with orgnr. The ad will be approved within 1-2 minutes. Else it will be manually administrated which can take 1-2 days.

**Comment by AlexSt2501** [comment]
Thanks a lot! Everything is ok now
