### ISSUE TITLE
Error: category 0000 does not exist

### ISSUE THREAD

**Issue by narius** [navikt/pam-import-api#36]
According to https://www.ssb.no/klass/klassifikasjoner/7 you have code "0000 - Uoppgitt / yrker som ikke kan identifiseres". When I send that code I get "Error: category 0000 does not exist" from you. Do you support all of ssb occupations or only some of them?

**Comment by tuantrannav** [comment]
Hi,

Yes we do support it, but it is identified as a "0" integer.

  "0" : {
    "styrkCode" : "0",
    "styrkDescription" : "Ikke konvertert",
    "categoryLevel1" : "Uoppgitt/ ikke identifiserbare",
    "categoryLevel2" : "Ikke identifiserbare"
  }
  
  You can take a look of all supported category here:
  https://arbeidsplassen-api.nav.no/stillingsimport/api/v1/categories/styrk/occupations
